{{- if and .Values.ollama.enabled .Values.ollama.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openprodoc.fullname" . }}-ollama-data
  labels:
    {{- include "openprodoc.ollama.labels" . | nindent 4 }}
  {{- with .Values.ollama.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.ollama.persistence.accessModes | nindent 4 }}
  {{- if .Values.ollama.persistence.storageClass }}
  storageClassName: {{ .Values.ollama.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size | quote }}
{{- end }}
