{{- if .Values.openwebui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openprodoc.fullname" . }}-openwebui
  labels:
    {{- include "openprodoc.openwebui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openwebui.service.type }}
  ports:
  - port: {{ .Values.openwebui.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "openprodoc.openwebui.selectorLabels" . | nindent 4 }}
{{- end }}
