{{- if .Values.pgvector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openprodoc.fullname" . }}-pgvector-secret
  labels:
    {{- include "openprodoc.pgvector.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.pgvector.config.password | b64enc | quote }}
{{- end }}
