{{- if and .Values.openwebui.enabled .Values.openwebui.watcher.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openprodoc.fullname" . }}-watcher-secret
  labels:
    {{- include "openprodoc.openwebui.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.openwebui.watcher.config.password | default "changeme" | quote }}
{{- end }}
